name: DevSecOps Security

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          cd smart-contracts
          forge install

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither
        run: |
          cd smart-contracts
          slither src/ --json ../reports/analyses/slither-report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: reports/analyses/slither-report.json
``
